### ISSUE TITLE
Error in docs / how do I call pull()/push() ?

### ISSUE THREAD

**Issue by rjmackay** [alekseykulikov/backbone-offline#10]
Your docs suggest calling push like this:
`dreams.sync.push()`

But this doesn't work as sync is undefined. Can you provide more info on how this is intended to be used?

**Comment by gilbert** [comment]
It's a typo in the readme. The real way to call it is:

``` coffeescript
# storage is the name of the variable that you set (@storage in the readme)
dreams.storage.sync.push()
```

**Comment by alekseykulikov** [comment]
Thank you @mindeavor for correct answer. It was a typo error and I fixed it. Project is a new and documentation still not perfect and has inaccuracies.

**Comment by masfusion** [comment]
This is still an issue and the call actually does nothing, I resume this is where the Collection should send data to the server, but no such call is made.
