### ISSUE TITLE
Save with @isNew()==true is called twice

### ISSUE THREAD

**Issue by ulitiy** [alekseykulikov/backbone-offline#13]
Model thinks, that it's created twice - locally and remotely
I don't know if it's expected behaviour, but my overriden function save, that checks @isNew works incorrectly.

**Comment by abuisman** [comment]
Same here. How did you solve this in the end? Or haven't you?

**Comment by ulitiy** [comment]
@abuisman, temporary solution is to use an additional parameter (local==true) to filter a local save

**Comment by abuisman** [comment]
@ulitiy Thanks, that worked:

```
# For future reference
@create data, {local: true}
```
