### ISSUE TITLE
Unwanted events

### ISSUE THREAD

**Issue by ulitiy** [alekseykulikov/backbone-offline#2]
Code like

```
  @collection.items.reset([]) #1 event
  @collection.items.create(item, local: true, regenerateId: true) for item in response #n events
  @collection.items.trigger('reset') #1 event
```

throws a lot of unwanted events, that browser should process (render views, other bindings)
there should be only 1 event - last

silent:true could help

**Comment by alekseykulikov** [comment]
Thanks @ulitiy. I want to do like this:

```
@collection.items.reset([], silent: true)
@collection.items.create(item, local: true, regenerateId: true, silent: true)
@collection.items.trigger('reset') #1 event
```

And add some specs for counting events.

**Comment by ulitiy** [comment]
I don't know if create supports silent, no information in docs.

**Comment by alekseykulikov** [comment]
Fixed it and added specs https://github.com/Ask11/backbone.offline/commit/be30f3c44933d467bb8128cbdf363c0d76b9389c
