### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by sontek** [alekseykulikov/backbone-offline#23]
The last commit was over a month ago and i'm wondering if this is still being used.

My needs:
1. Work completely offline, so create client ids as GUIDs
2. Sync to the server

Are these handles by this library?

**Comment by alekseykulikov** [comment]
Yes, it's, but with restrictions. I'm going to start work on new version soon: https://github.com/Ask11/backbone.offline/issues/21 and it will definitely helps you. Now you're welcome to share your experience and ideas.

**Comment by sontek** [comment]
@Ask11  Great!  Yesterday I wrote a plugin that sits on top of Backbone.localStorage http://paste2.org/p/2472330  which does most of what I want, but it doesn't have a sync algorithm.  It just works with localStorage and the server at the same time.

**Comment by sontek** [comment]
@Ask11  Hows the progress of 21 coming?

**Comment by alekseykulikov** [comment]
I've still haven't started it, working on another parts in my project, but I should in December :) Your plugin looks very interesting, maybe you will just merge my sync algorithm with your's plugin?)
