### ISSUE TITLE
Compatibility with Backbone 0.9.10

### ISSUE THREAD

**Issue by toxygene** [alekseykulikov/backbone-offline#28]
The latest version of backbone.offline is not compatible with Backbone 0.9.10.

**Comment by alekseykulikov** [comment]
Oh, new version of Backbone is available, thanks for remain! Going to fix on next week.

**Comment by zeopix** [comment]
thank you very mach for this update!

**Comment by efonsecab** [comment]
I'm having an issue in my application where, the each time I use fetch, it adds the same items to the collection. incrasing size of collection by a lot due to duplicfated items.
Anyone has any idea why this would happen

**Comment by mattzeunert** [comment]
The two issues probably aren't related, unless it works if you use Backbone 0.9.9.

**Comment by efonsecab** [comment]
I does work fine if I do not use Backbone.offline and instead always get data from the server. That is the weird thing

**Comment by alekseykulikov** [comment]
Guys, sorry about unnecessary mess with 0.9.10. Fixed all bugs: https://github.com/Ask11/backbone.offline/commit/e6177edda9a74790f0561ded15cf3ac8d1457ccc and updated dreamy to Backbone 0.9.10, be sure that you refreshed page twice http://dreamyapp.herokuapp.com/.
