### ISSUE TITLE
Support Collection#parse() for non-standard APIs

### ISSUE THREAD

**Issue by hardchor** [alekseykulikov/backbone-offline#35]
Backbone collections provide an alternative callback when fetching data from a non-standard API:
http://backbonejs.org/#Collection-parse

I've been running into problems trying to get backbone.offline to work and started working on some fixes. 
I'll send a pull request if support for this is something you'd like to see in backbone.offline and I've got it working flawlessly.

**Comment by alekseykulikov** [comment]
Hi @hardchor, yes, it's missing in current backbone.offline implementation and it definitely will very helpful. Would be nice to see your pul request.

**Comment by hardchor** [comment]
Not written any coffeescript so far (mainly because I think it's stupid ;) ) but will try my best.

**Comment by alekseykulikov** [comment]
Good luck with coffeescript, btw, new version of backbone.offline will write on clean javascript :)
