### ISSUE TITLE
Fetch Local dont work with Backbone 1.0

### ISSUE THREAD

**Issue by kprimdal** [alekseykulikov/backbone-offline#39]
I just updated to Version 1.0 of Backbone and then fetch({local: true}) does not work anymore.

When running that command, if just add a new instance of the Collection in the collection.

**Comment by alekseykulikov** [comment]
Hi @kprimdal, I've not tested backbone.offline with Backbone 1.0 yet, need to try.

**Comment by spencernowak** [comment]
Found the issue on line 27 of the JS file:
`return options.success(model, (_ref = resp.attributes) != null ? _ref : resp, options);`

BB 1.0 expects the response as the first argument. Change the line to:
`return options.success((_ref = resp.attributes) != null ? _ref : resp, options);`
and it will stop nesting another collection on local fetch.

**Comment by kprimdal** [comment]
Great work @spencernowak, thanks for letting us know

**Comment by alekseykulikov** [comment]
Done. New 0.5.0 version supports only Backbone 1.0.0.
