### ISSUE TITLE
"Record Not Found" when fetching a model

### ISSUE THREAD

**Issue by toxygene** [alekseykulikov/backbone-offline#42]
I'm trying to fetch a single model, but I'm running into issues:

``` javascript
var Foo = Backbone.Model.extend({
    initialize: function() {
        this.storage = new Offline.Storage("foo", this);
    },
    url: "foo.json"
});

var bar = new Foo({id: 1});
bar.fetch({error: function(reason) {
    console.error(reason);
}, success: function() {
    console.log(arguments);
}});
```

This code causes a "Record Not Found" error. Is fetching a single model not supported by Backbone.Offline or am I doing something wrong?

**Comment by valerianrossigneux** [comment]
I've exactly this. Seems that the fetch does't go to the server to get the model.

Any help?

**Comment by valerianrossigneux** [comment]
Seems that find https://github.com/ask11/backbone-offline/blob/master/js/backbone_offline.js#L121 function is only retrieving local data compared to findAll
