### ISSUE TITLE
Server implementation

### ISSUE THREAD

**Issue by valerianrossigneux** [alekseykulikov/backbone-offline#47]
Hi! Do you have any server sync implementation to recommend (PHP and mysql, node.js and mongodb, node.js and mysql, ...)?

Regards,
Valérian

**Comment by alekseykulikov** [comment]
Hey! Check the [dreamy](https://github.com/ask11/dreamy) as example it uses rails and postgres.

**Comment by valerianrossigneux** [comment]
Thanks, I'll check this. Do you know any existing backbone-module running node.js and doing this?

**Comment by alekseykulikov** [comment]
You're welcome. I actually tried to use it with node https://github.com/ask11/backbone-offline/tree/edge/examples/notepad, but have not finished yet. Too busy with my job.
